-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-137, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue Organization sprocs to thread CreatedByUserId / ModifiedByUserId
--   through Create / Update and to expose them on Read sprocs. New params
--   default to NULL so the migration is safe to run before services are
--   redeployed (old callers keep working).
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/organization/sql/dbo.organization.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateOrganization
--   dbo.ReadOrganizations
--   dbo.ReadOrganizationById
--   dbo.ReadOrganizationByPublicId
--   dbo.ReadOrganizationByName
--   dbo.UpdateOrganizationById
--   dbo.DeleteOrganizationById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
