-- Phase 0 — Access Control Rebuild
-- Update Read sprocs on dbo.[User] to also return the new access-control
-- discriminator columns (IsSystemAdmin, IsAgent, LastCompanyId).
-- CreateUser / UpdateUserById / DeleteUserById are NOT touched — those
-- columns get dedicated mutation sprocs in Phase 1+.
-- Idempotent (CREATE OR ALTER).

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-131, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Phase 0 — Access Control Rebuild
--   Update Read sprocs on dbo.[User] to also return the new access-control
--   discriminator columns (IsSystemAdmin, IsAgent, LastCompanyId).
--   CreateUser / UpdateUserById / DeleteUserById are NOT touched — those
--   columns get dedicated mutation sprocs in Phase 1+.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user/sql/dbo.user.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadUsers
--   dbo.ReadUserById
--   dbo.ReadUserByPublicId
--   dbo.ReadUserByFirstname
--   dbo.ReadUserByLastname
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-126, 2026-07-23) — sproc body removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Persist the user's last active Company on switch-company.
--
-- The canonical definition of this sproc now lives in exactly ONE place:
--   entities/user/sql/dbo.user.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.SetUserLastCompanyId
--
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
