-- Phase 1 — Access Control Rebuild
-- Re-issue User Create/Update/Delete sprocs to thread CreatedByUserId
-- and ModifiedByUserId. Read sprocs already SELECT them (Phase 0 002).
-- New params default to NULL.
-- Idempotent (CREATE OR ALTER).

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-131, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue User Create/Update/Delete sprocs to thread CreatedByUserId
--   and ModifiedByUserId. Read sprocs already SELECT them (Phase 0 002).
--   New params default to NULL.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user/sql/dbo.user.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateUser
--   dbo.UpdateUserById
--   dbo.DeleteUserById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
