-- Phase 4 — Access Control Rebuild — IsAgent filter on user lists.
-- Adds @IncludeAgents BIT = 0 to ReadUsers. Default behavior changes:
-- agent users (User.IsAgent = 1) are hidden from the list. Pass
-- @IncludeAgents = 1 to surface them (e.g. for an admin Agents tab).
--
-- Idempotent (CREATE OR ALTER). Safe to re-run.
--
-- Direct lookups (ReadUserById, ReadUserByPublicId, ReadUserByFirstname,
-- ReadUserByLastname) are NOT filtered — if the caller has the Id /
-- PublicId / name, they want that specific row.

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-131, 2026-07-23) — sproc body removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Phase 4 — Access Control Rebuild — IsAgent filter on user lists.
--   Adds @IncludeAgents BIT = 0 to ReadUsers. Default behavior changes:
--   agent users (User.IsAgent = 1) are hidden from the list. Pass
--   @IncludeAgents = 1 to surface them (e.g. for an admin Agents tab).
--   Idempotent (CREATE OR ALTER). Safe to re-run.
--
-- The canonical definition of this sproc now lives in exactly ONE place:
--   entities/user/sql/dbo.user.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadUsers
--
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
