-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-126 + U-133, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue UserModule sprocs to thread CompanyId, CreatedByUserId,
--   ModifiedByUserId. Adds ReadUserModulesByUserIdAndCompanyId for the
--   Phase 2 permission resolver. New params default to NULL.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user_module/sql/dbo.usermodule.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadUserModulesByUserIdAndCompanyId  (U-126)
--   dbo.CreateUserModule  (U-133)
--   dbo.ReadUserModules
--   dbo.ReadUserModuleById
--   dbo.ReadUserModuleByPublicId
--   dbo.ReadUserModuleByUserId
--   dbo.ReadUserModulesByUserId
--   dbo.ReadUserModuleByModuleId
--   dbo.UpdateUserModuleById
--   dbo.DeleteUserModuleById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
