-- Move VendorCreditLineItemBillCreditLineItem mapping sprocs into dbo (2026-06-18).
-- These were created in the [qbo] schema, but call_procedure() always issues
-- "EXEC dbo.{name}", so every call resolved to a non-existent dbo proc and failed.
-- Symptom: the mapping create was silently swallowed (warning) so the table was
-- effectively unpopulated (4 rows vs Bill's ~22k); the new upsert path's
-- read_by_qbo_line_id errored on every credit line. Recreate in dbo to match
-- Bill's convention + call_procedure. The TABLE stays in the qbo schema.
-- Idempotent (CREATE OR ALTER). Old qbo.* copies are harmless (unused).
--   python scripts/run_sql.py scripts/migrations/qbo_vendorcredit_mapping_sprocs_dbo.sql

--
-- U-361: the four sproc bodies this file used to declare
-- (CreateVendorCreditLineItemBillCreditLineItem,
--  ReadVendorCreditLineItemBillCreditLineItemByQboLineId,
--  ReadVendorCreditLineItemBillCreditLineItemByBillCreditLineItemId,
--  DeleteVendorCreditLineItemBillCreditLineItemById — known-dups of the
-- connector's qbo.vendorcredit_line_item_bill_credit_line_item.sql copies, per
-- tests/sproc_drift_ledger.py) were removed here together with that base file:
-- qbo.VendorCreditLineItemBillCreditLineItem is retired (U-349 program family
-- 8/11). dbo.BillCreditLineItem.QboId/RealmId, parent-scoped, is the sole line
-- identity store; /em drops the live table + sprocs post-deploy. Kept as a
-- pointer stub for the migration history only — nothing to run.
