-- =============================================================================
-- 2026-05-27 — Phase 5: re-issue AggregateTimeEntryOnSubmit to stamp
-- SourceTimeEntryId on the ContractLabor path.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-125, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   ContractLabor SourceTimeEntryId stamping on aggregate submit.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/time_entry/sql/dbo.time_entry.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.AggregateTimeEntryOnSubmit
--
-- NOTE: this file's AggregateTimeEntryOnSubmit body was STALE vs live prod (live == migration 009's body) — re-running it would have reverted prod.
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
