-- =============================================================================
-- 2026-05-27 — Phase 5: downstream-lock check sproc.
-- IsTimeEntryDownstreamLocked(@TimeEntryId) — block edits when billed/invoiced.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-125, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Downstream terminal-state lock check for TimeEntry mutations.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/time_entry/sql/dbo.time_entry.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.IsTimeEntryDownstreamLocked
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
