-- =============================================================================
-- 2026-06-16 — Time-Entry daily digest support + MS outbox idempotency count.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-125, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Morning per-worker digest resolver + generic MS outbox entity count.
--
-- Each sproc's canonical definition now lives in exactly one place:
--   entities/time_entry/sql/dbo.time_entry.sql  (ReadTimeEntriesForDigestByWorkDate)
--   integrations/ms/outbox/sql/ms.outbox.sql  (CountMsOutboxByEntity)
--
-- Sprocs formerly defined here (now canonical in the base files):
--   dbo.ReadTimeEntriesForDigestByWorkDate
--   dbo.CountMsOutboxByEntity
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
