-- =============================================================================
-- 2026-06-16 — batch read TimeLogs for a list of TimeEntry IDs (list ?include_logs=true).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-125, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Batch TimeLog hydration for the time-entries list endpoint.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/time_entry/sql/dbo.time_entry.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadTimeLogsByTimeEntryIds
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
