-- Migration 015: deterministic Id tie-break on TimeEntry current-status reads
-- TimeEntryStatus.CreatedDatetime is DATETIME2(3); reject() writes rejected+draft in two
-- back-to-back SYSUTCDATETIME() calls that can collide at the same ms. Adding a secondary
-- , [Id] DESC/ASC sort key makes the current-status pick + history list deterministic.
-- Originally redefined: ReadTimeEntriesPaginated, CountTimeEntries, ReadCurrentTimeEntryStatus (Id DESC picks)
-- + ReadTimeEntryStatusesByTimeEntryId (Id ASC history list). ORDER-BY-only; no logic/row-set/shape change.
-- U-037: sprocs are now RBAC-scoped (@ActorUserId / @ActorIsSystemAdmin / @ActorCanViewTeam).

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-045, 2026-07-16) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Id tie-break on TimeEntryStatus ORDER BY for deterministic current-status reads.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/time_entry/sql/dbo.time_entry.sql
--
-- Sprocs formerly redefined here (now canonical in the base file):
--   dbo.CountTimeEntries, dbo.ReadCurrentTimeEntryStatus, dbo.ReadTimeEntriesPaginated,
--   dbo.ReadTimeEntryStatusesByTimeEntryId
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
