-- Migration 016 originally added the @SortBy='Worker' ORDER-BY branch to ReadTimeEntriesPaginated
-- (u.Lastname then u.Firstname, honoring @SortDirection); ORDER-BY-only, no signature/scope/row-set change;
-- preserves the 13-param RBAC-scoped signature and the 3-way fail-closed scope clause.
-- Also appends te.[Id] ASC as the final ORDER BY key so the sort is total and OFFSET/FETCH pagination is deterministic.

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-045, 2026-07-16) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Worker sort ORDER-BY branch on ReadTimeEntriesPaginated for list-page pagination.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/time_entry/sql/dbo.time_entry.sql
--
-- Sprocs formerly redefined here (now canonical in the base file):
--   dbo.ReadTimeEntriesPaginated
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
