-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-140, 2026-07-24) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue Company sprocs to thread OrganizationId, CreatedByUserId,
--   and ModifiedByUserId. New params default to NULL so the migration is
--   safe to run before services are redeployed.
--   The NOT NULL flip on Company.OrganizationId lands in a separate
--   migration once services are caught up.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/company/sql/dbo.company.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateCompany
--   dbo.ReadCompanies
--   dbo.ReadCompanyById
--   dbo.ReadCompanyByPublicId
--   dbo.ReadCompanyByName
--   dbo.UpdateCompanyById
--   dbo.DeleteCompanyById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
