-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-148, 2026-07-24) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Update the five Attachment read sprocs to include extraction fields
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/attachment/sql/dbo.attachment.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadAttachments
--   dbo.ReadAttachmentById
--   dbo.ReadAttachmentByPublicId
--   dbo.ReadAttachmentByCategory
--   dbo.ReadAttachmentByHash
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
