-- Phase 1 — Access Control Rebuild
-- Re-issue UserProject sprocs to thread CreatedByUserId / ModifiedByUserId.
-- Adds ReadUserProjectsByUserId (plural) so the Phase 3 row-scope
-- resolver can fetch all projects for a user in one shot.
-- Idempotent (CREATE OR ALTER).

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-129, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue UserProject sprocs to thread CreatedByUserId / ModifiedByUserId.
--   Adds ReadUserProjectsByUserId (plural) so the Phase 3 row-scope
--   resolver can fetch all projects for a user in one shot.
--   Idempotent (CREATE OR ALTER).
--   (NB the plural ReadUserProjectsByUserId was never actually defined in
--   this file or anywhere else in the repo — the header over-promised;
--   only the singular ReadUserProjectByUserId below ever shipped.)
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user_project/sql/dbo.userproject.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateUserProject
--   dbo.ReadUserProjects
--   dbo.ReadUserProjectById
--   dbo.ReadUserProjectByPublicId
--   dbo.ReadUserProjectByUserId
--   dbo.ReadUserProjectByProjectId
--   dbo.UpdateUserProjectById
--   dbo.DeleteUserProjectById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
