-- Phase 1b — Review Notifications
-- Re-issues UserProject sprocs to thread @RoleId. Read sprocs LEFT JOIN
-- dbo.Role to surface RoleName denormalized for the recipient resolver
-- and React UI dropdowns. @RoleId defaults to NULL so callers that
-- haven't been updated still work (existing UserProject rows stay
-- unclassified).
-- Idempotent (CREATE OR ALTER).

-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-129, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Phase 1b — Review Notifications
--   Re-issues UserProject sprocs to thread @RoleId. Read sprocs LEFT JOIN
--   dbo.Role to surface RoleName denormalized for the recipient resolver
--   and React UI dropdowns. @RoleId defaults to NULL so callers that
--   haven't been updated still work (existing UserProject rows stay
--   unclassified).
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user_project/sql/dbo.userproject.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateUserProject
--   dbo.ReadUserProjects
--   dbo.ReadUserProjectById
--   dbo.ReadUserProjectByPublicId
--   dbo.ReadUserProjectByUserId
--   dbo.ReadUserProjectByProjectId
--   dbo.UpdateUserProjectById
--   dbo.DeleteUserProjectById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
