-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-100, 2026-07-21) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Migration 003 — add `SourceEmailMessageId` to Bill Read/Update/Delete sproc
--   projections.
--
--   Context: 2026-05-19 manual backlog walk surfaced that
--   BillRepository.read_by_id returned `source_email_message_id=None` for
--   Bill 18545 even though the underlying row had `SourceEmailMessageId=752`
--   (just-written by CreateBill seconds earlier). Root cause: ReadBillById
--   — and by extension every sibling Read* / OUTPUT projection — never
--   included the column. CreateBill wrote it; nothing else read it back.
--   Bill dataclass had the field (with a comment acknowledging the gap);
--   _from_db used getattr defensively. Pure additive fix:
--   include the column in 8 sproc projections in entities/bill/sql/dbo.bill.sql.
--
--   Why a migration file: dbo.bill.sql has a pre-existing
--   BillCompletionResult.ExpiresAt sproc breakage (TODO.md line 196) that
--   blocked re-running the canonical file. Same workaround as the
--   LinkBillSourceEmailMessage migration (dbo.bill_create_source_email.sql).
--
--   Idempotent: CREATE OR ALTER on each sproc. Re-applying is safe.
--
-- The canonical definitions now live in exactly ONE place:
--   entities/bill/sql/dbo.bill.sql
--
-- Sprocs formerly redefined here:
--   ReadBills, ReadBillById, ReadBillByPublicId, ReadBillByBillNumber,
--   ReadBillByBillNumberAndVendorId, UpdateBillById, DeleteBillById,
--   ReadBillsPaginated
--
-- Re-running this file is now a no-op. Do NOT reintroduce bodies here.
--
-- DANGER (motivated U-100): this file's ReadBills and ReadBillsPaginated are
-- the UNSCOPED pre-RBAC form (no @ActorUserId / UserCanAccessBill filter) and
-- its UpdateBillById writes [DueDate]=@DueDate, reverting the DueDate=BillDate
-- rule enforced in the canonical base file. Re-applying would unscope Bill list
-- reads and silently revert DueDate mirroring.
-- ---------------------------------------------------------------------------

GO

PRINT 'SUPERSEDED (U-100): no sprocs applied; canonical definitions live in entities/bill/sql/dbo.bill.sql.';
