-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-071, 2026-10-08) — sproc body removed, NOT the intent.
--
-- Original intent of this migration (preserved for lineage):
--   ReadProjectsByUserId — add @ActorIsSystemAdmin bypass. When
--   ActorIsSystemAdmin = 1, return all projects without requiring
--   UserProject membership (same pattern as Phase 3 TimeEntry scoping).
--   Closes the gap where IsSystemAdmin=1 users only saw projects they had
--   explicit UserProject rows for.
--
-- The canonical definition of this sproc now lives in exactly ONE place:
--   entities/project/sql/dbo.project.sql
--
-- Re-running this file is now a no-op. Do NOT reintroduce a body here — a
-- copy that drifts from the base file silently reverts the base (U-071 added
-- the Customer join there; this file would have removed it on re-apply).
-- ---------------------------------------------------------------------------
