-- =============================================================================
-- Task Inbox sprocs — reads the cross-entity reviewer worklist.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-126, 2026-07-23) — sproc bodies removed, NOT the intent.
--
-- Original intent of this section (preserved for lineage):
--   Cross-entity reviewer task inbox list + sidebar count sprocs.
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/review/sql/dbo.inbox_tasks.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadInboxTasks
--   dbo.ReadInboxTaskCounts
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
