-- =============================================================================
-- 2026-06-09 — Restrict review notification recipients to real human users.
--
-- Excludes two non-human classes from the recipient walk:
--   (a) LLM agent accounts — dbo.User.IsAgent = 1
--   (b) Persona test accounts — dbo.Auth.Username starting with 'persona_'
--
-- Personas are end-to-end test accounts seeded by intelligence/persistence/sql/
-- seed.personas.sql (UserIds 55-61):
--   persona_owner / persona_tenant_admin / persona_controller /
--   persona_project_manager / persona_field_crew / persona_intern /
--   persona_sysadmin
-- Each persona is linked into every active project's UserProject (with the
-- right RoleId on Owner/PM rows). Deliberate for cross-flow notification
-- testing — without this filter, every review draft TO/CC included
-- persona.project.manager@buildone.test / persona.owner@buildone.test
-- alongside the real PMs/Owners.
--
-- Filter applied identically in each resolver's role-walk CTE:
--   AND NOT EXISTS (
--       SELECT 1 FROM dbo.[User] u
--       WHERE u.[Id] = up.[UserId] AND u.[IsAgent] = 1
--   )
--   AND NOT EXISTS (
--       SELECT 1 FROM dbo.[Auth] a
--       WHERE a.[UserId] = up.[UserId]
--         AND LEFT(LTRIM(a.[Username]), 8) = N'persona_'
--   )
--
-- LTRIM defends against an accidental leading-whitespace Auth.Username
-- bypassing the prefix match. N-prefix preserves the v2 sproc's literal
-- discipline.
--
-- The persona prefix is reserved-by-convention: any future legitimate
-- user must not have an Auth.Username starting with 'persona_'.
--
-- Three sprocs touched:
--   1. dbo.ResolveReviewRecipientsByBillId           (supersedes 001)
--   2. dbo.ResolveReviewRecipientsByContractLaborId  (supersedes 004)
--   3. dbo.ResolveContractLaborReviewRecipientsPerProject (supersedes 007)
--
-- *** Migration ordering note ***
-- If 001, 004, or 007 is ever re-applied AFTER 008, the human-only filter
-- is wiped. Header comments in those files now warn against that.
--
-- Verified pre-migration via DB query: filter matches all 7 seeded personas
-- (UserIds 55-61) and no false positives across the ~100 non-persona
-- accounts. Empirical side-by-side on ContractLabor 597 (Wilmer Diaz):
-- 4 recipients before → 2 after (drops Persona Owner + Persona PM, keeps
-- Austin Rogers + Tanner Baker).
--
-- Idempotent (CREATE OR ALTER). Safe to re-run.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Bill resolver — filter personas in UserProjectRoles
-- -----------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-062) — sproc body removed, NOT the intent.
-- Canonical definition now lives in exactly ONE place:
--   entities/review/sql/dbo.review.sql
-- Sproc formerly redefined here: dbo.ResolveReviewRecipientsByBillId
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is the single-source hazard.
-- ---------------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- 2. ContractLabor resolver — filter personas in UserProjectRoles
-- -----------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-062) — sproc body removed, NOT the intent.
-- Canonical definition now lives in exactly ONE place:
--   entities/review/sql/dbo.review.sql
-- Sproc formerly redefined here: dbo.ResolveReviewRecipientsByContractLaborId
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is the single-source hazard.
-- ---------------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- 3. Per-project ContractLabor resolver (v2 envelope, includes Owners)
-- -----------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-062) — sproc body removed, NOT the intent.
-- Canonical definition now lives in exactly ONE place:
--   entities/review/sql/dbo.review.sql
-- Sproc formerly redefined here: dbo.ResolveContractLaborReviewRecipientsPerProject
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is the single-source hazard.
-- ---------------------------------------------------------------------------


PRINT 'SUPERSEDED (U-062): no sprocs applied; canonical definitions live in entities/review/sql/dbo.review.sql.';
