-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-162, 2026-07-28) — sproc body removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Deploy ReadContractLaborByNaturalKey (duplicate detection on import).
--
-- The canonical definition of this sproc now lives in exactly ONE place:
--   entities/contract_labor/sql/dbo.contract_labor.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadContractLaborByNaturalKey
--
-- Drift: this standalone was the STALE side (missing [SourceTimeEntryId],
-- predates the 2026-05-27 SourceTimeEntryId migration); the base was already live.
--
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
GO
