-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-162, 2026-07-28) — sproc body removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   ReadContractLaborDailySummary with SET NOCOUNT ON (commit a84fd4f — premise
--   later refuted: assignment-only SELECT @var = … does NOT break pyodbc on prod;
--   verified 2026-07-28; real break is DML→row-returning-SELECT + fetchone()).
--
-- The canonical definition of this sproc now lives in exactly ONE place:
--   entities/contract_labor/sql/dbo.contract_labor.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadContractLaborDailySummary
--
-- Drift: U-162 reconciled the base to the LIVE prod body (assignment-only SELECTs,
-- pointless BEGIN TRANSACTION/COMMIT on a read-only sproc). U-164 added SET NOCOUNT ON
-- and removed the read-only transaction as hygiene.
--
-- Re-running this file is now a no-op for this sproc. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
GO
