-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-126 + U-144, 2026-07-24) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue UserRole sprocs to thread CompanyId, CreatedByUserId,
--   ModifiedByUserId. Adds ReadUserRolesByUserIdAndCompanyId for the
--   Phase 2 permission resolver. New params default to NULL.
--   The NOT NULL flip + new (UserId, CompanyId, RoleId) unique land in
--   a separate migration once services are caught up.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user_role/sql/dbo.userrole.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.ReadUserRolesByUserIdAndCompanyId  (U-126)
--   dbo.CreateUserRole  (U-144)
--   dbo.ReadUserRoles
--   dbo.ReadUserRoleById
--   dbo.ReadUserRoleByPublicId
--   dbo.ReadUserRoleByUserId
--   dbo.ReadUserRoleByRoleId
--   dbo.ReadUserRolesByUserId
--   dbo.UpdateUserRoleById
--   dbo.DeleteUserRoleById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
