-- ---------------------------------------------------------------------------
-- SUPERSEDED (U-146, 2026-07-24) — sproc bodies removed, NOT the intent.
--
-- Original intent of this file (preserved for lineage):
--   Phase 1 — Access Control Rebuild
--   Re-issue UserCompany sprocs to thread CreatedByUserId / ModifiedByUserId.
--   Idempotent (CREATE OR ALTER).
--
-- The canonical definition of these sprocs now lives in exactly ONE place:
--   entities/user_company/sql/dbo.usercompany.sql
--
-- Sprocs formerly defined here (now canonical in the base file):
--   dbo.CreateUserCompany
--   dbo.ReadUserCompanies
--   dbo.ReadUserCompanyById
--   dbo.ReadUserCompanyByPublicId
--   dbo.ReadUserCompanyByUserId
--   dbo.ReadUserCompaniesByUserId
--   dbo.UpdateUserCompanyById
--   dbo.DeleteUserCompanyById
--
-- Re-running this file is now a no-op for these sprocs. Do NOT reintroduce a
-- body here — a copy that drifts from the base file is what caused the
-- 2026-07-15 outage (SQL 8144, cross-user payroll exposure risk).
-- ---------------------------------------------------------------------------
